spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:your_db_name}?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  application:
    openApi:
      title: Redis API
      description: Redis API
      version: 1.0
      license:
        name: Apache License Version 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0
      name: Redis API
      url: http://localhost:8083
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
      refreshable-duration: ${JWT_REFRESHABLE_DURATION}
      valid-duration: ${JWT_VALID_DURATION}
  api:
    prefix: /api/
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  trello:
    api-key: ${TRELLO_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
executor:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 100
  thread-name-prefix: background-job-thread